Adding Submitted Bios
newtheatre/history-project pull request #1702
Opened 2021-11-27 13:36 UTC by BenWoodford76

Adding bios submitted from the person collect form

2021-12-09 11:17 UTC, samozzy requested changes

2021-12-09 11:17 UTC, samozzy commented on _committees/07_08.md
> +    note: Took over after Sam Turnbull stepped down
Can we add a `(dates unknown)` to these as a mini call to action for more info? Thoughts?

2021-12-09 11:17 UTC, samozzy commented on _people/annabel_byrom.md
> +<!-- Content for a bio here -->
This line can go away

2021-12-09 11:17 UTC, samozzy commented on _people/john_schwiller.md
> +I then joined CCT Theatre Lighting where I spent 10yrs as Technical Director, designing lighting equipment as seen in Abbas Super Trouper, Human Leagues Dont You Want Me, Cats, a Joe Jackson tour and
Can we get some apostrophes in here please?

2021-12-09 11:17 UTC, samozzy commented on _shows/05_06/the_slippery_soapbox_edinburgh.md
> +  - role: Graham/Leotard Man
Spaces around the `/` please

2021-12-09 11:19 UTC, samozzy commented on _shows/01_02/cabaret.md
> + - role: Band, Trombone
Can this be
```
role: Band
note: Trombone
```
Which I think then matches up with our other formats, as I don't think there's a programme formatted in that way for this show.

2021-12-11 10:50 UTC, BenWoodford76 commented
@samozzy think i've addressed everything :)

2021-12-11 12:21 UTC, samozzy approved these changes

2021-12-11 12:24 UTC, samozzy approved these changes

2021-12-11 12:27 UTC, merged